import numpy as np
#arr1 = np.array([10,20,30,40,50])
#print(arr1)
#arr2 = np.array([[1,2,3],[4,5,6]])
#print(arr2)
#zeros = np.zeros((2,3))
#print(zeros)
#ones = np.ones((3,2))
#print(ones)
#arange_arr = np.arange(0, 10, 2)
#print(arange_arr)

#arr = np.array([10,20,30,40,50])
#print(arr[0]) 
#print(arr[-1])
#arr2 = np.array([[1,2,3],[4,5,6]])
#print(arr2[0, 1])
#print(arr2[1, -1])

#arr = np.array([[1, 2, 3], [4, 5, 6]])
#transposed1 = np.transpose(arr)
#print("Original : \n", arr)
#print("Transposed : \n", transposed1)

arr = np.array([1, 2, 3, 4])
print(arr+10)
print(arr**2)
print(arr*2)
arr = np.array([5,10,15,20])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
arr = np.arange(1,13)
reshaped = arr.reshape(3, 4)
print(reshaped)
arr = np.array([3,1,4,1,5,9])
sorted_arr = np.sort(arr)
print(sorted_arr)
arr = np.array([10,25,5,40])
print(arr[arr > 20])
names = np.array(['Alice', 'Bob', 'Charlie'])
print(np.char.upper(names))
print(np.char.count(names, 'a'))